### ISSUE TITLE
[feature request] surface dice

### ISSUE THREAD

**Issue by neuronflow** [rundherum/pymia#26]
Please add the surface dice score, which is increasingly used in challenges. Thanks!

**Comment by fabianbalsiger** [comment]
@neuronflow I just noticed that this is already implemented. See `SurfaceDiceOverlap` in the module `pymia.evaluation.metric.segmentation`. Note that also `SurfaceOverlap` is implemented.
Closing for now. Please reopen the issue if you have further questions.
