### ISSUE TITLE
Distance metrics do not work for 2-D images

### ISSUE THREAD

**Issue by fabianbalsiger** [rundherum/pymia#27]
Metrics based on the `Distances` class do not work for 2-D images. Maybe we need a fallback to SimpleITK in this case?

**Comment by neuronflow** [comment]
Just wanted to open an issue for you, I assume this is based on my msg from yesterday? :)
I just wanted to code a workaround and convert my 2d images to 3d, but it seems you are already in the process of fixing it?

**Comment by fabianbalsiger** [comment]
@neuronflow I just fixed the issue. Do you also need a new PyPI package version?

**Comment by neuronflow** [comment]
very cool, thanks! I cannot estimate how much effort the build and release requires from your side.

If you choose not to release yet, I should simply use the 2nd installation option from Github here, right?
https://pymia.readthedocs.io/en/latest/installation.html

**Comment by fabianbalsiger** [comment]
Yes, you can use the 2nd installation option. Just remove the old installation first (`pip uninstall pymia`).
Reopen the issue if you still encounter problems!
