### ISSUE TITLE
[Question] Is there a way to create a metadata h5 with a multiple dicom file stack?

### ISSUE THREAD

**Issue by RyanMelaugh** [rundherum/pymia#39]
The context, the volume is composed of multiple dicom files not a single file for the stack.
With a single volume I could save the metadata by assigning each file a unique key (just a number from iteration) as part of the subjects image dictionary.

The problem is, that when trying to save more than one volume, it is expected that the dictionaries match and each volume has a variable number of slices and thus files.
It returns the error
`ValueError: Inconsistent images identifiers in the subject list`

Is there a way to achieve this without resaving the volumes as single files?
Resaving them isn't very viable in this case, it would double storage of a considerable amount of data since we still need to maintain the volume as individual files for each slice.

Here is the code I currently have which works for a single volume
```class Subject(data.SubjectFile):
    def __init__(self, subject: str, data_files, lbl_files):
        # convert file lists to dictionaries
        file_dict = {f"{i}_original": file for i, file in enumerate(data_files)}
        lbl_dict = {f"{i}_lbl": file for i, file in enumerate(lbl_files)}
        super().__init__(
            subject,
            images=file_dict,
            labels=lbl_dict,
        )
        self.subject_path = f"/home/ubuntu/Data/{subject}"```

**Comment by fabianbalsiger** [comment]
Hi,

do I get your problem right that `data_files` and `lbl_files` are lists of DICOM files? For each subject, the list can have a different number of image slices, i.e., DICOM files? If this is correct, then you could pass a list of the file identifiers for each image volume to `images` and `labels` like `images={'Image1': data_files}, labels={'Label1': lbl_files}`. Then, in your LoadData class, you could handle the DICOM loading, something like:

```
class LoadData(file_load.Load):

    def __call__(self, file_names, id_: str, category: str, subject_id: str) -> \
            typing.Tuple[np.ndarray, typing.Union[conv.ImageProperties, None]]:
        if id_ == 'Image1':
                # load your DICOM file by using file_names (the list)
                return value, properties
```

Like this, there is no need to resave the DICOM files as single images. The code is untested but I think it might work. As I am not sure if I understood your problem correctly, feel free to come back to us if it doesn't work!

**Comment by RyanMelaugh** [comment]
Thanks for the quick response Fabian!

You are correct, that is the setup. I think though my problem is in the callbacks.

If I just use the WriteEssential callback, it does create the H5, and I can tell the loader must have worked as it has correctly written out the volume shapes.
When I compose the callbacks with the WriteFiles as well, the error pops up that it expected a string object rather than list. 
Which makes sense when I read the code. I'm guessing then I need to create a custom writefile callback in that case?
I don't mind of course just wanted to clarify I'm not being a bit of an idiot.

**Comment by fabianbalsiger** [comment]
Dear Ryan,

Yes, you are correct. You either need to write your own `WriteFilesCallback` or simply don't use it. This callback basically only writes the file names for reference/reproducibility to the dataset. So the solution is up to you. I will close the issue, feel free to reopen (or even open a new issue) if you have further questions.
