### ISSUE TITLE
using evaluation example

### ISSUE THREAD

**Issue by jakubMitura14** [rundherum/pymia#41]
in basic evaluation example notebook in my case to make it work I needed to change line

prediction = sitk.BinaryErode(prediction, 1, sitk.sitkBall, 0, label_val)

into

prediction = sitk.BinaryErode(prediction, [1,1,1], sitk.sitkBall, 0, label_val)

**Comment by fabianbalsiger** [comment]
Thank you very much for your issue. You are right, since SimpleITK 2.0 only vector parameters are accepted, [see Migration Guide 2.0](https://simpleitk.readthedocs.io/en/release/migrationGuide2.0.html#morphology-radius). I will fix this bug asap.

**Comment by jakubMitura14** [comment]
Glad was able to help, also question did you completed some benchmarks? and is the code for benchmarking is available ?

**Comment by fabianbalsiger** [comment]
@jakubMitura14 What do you mean by benchmarks? To date, we did not do any benchmarking (e.g., time to calculate metrics) beyond what's written in the [paper](https://doi.org/10.1016/j.cmpb.2020.105796).
