### ISSUE TITLE
rand index and cohen cappa problem 

### ISSUE THREAD

**Issue by jakubMitura14** [rundherum/pymia#42]
Hello using example notebook i downloaded  the  example dataset, I tried for the moment for patient2, I calculated all binary non distance metrics and compared results tha I calculated manually using  Taha code ( https://github.com/Visceral-Project/EvaluateSegmentation/blob/master/source/CohinKappaMetric.h) in 2 cases I have discrepancy 

In case of rand Index pymia is evaluating to 1.163 and my code 0.618699 ; also by definition of metric I suppose it should not be above 1 ?
 for cohen cappa I got 0.6401 and pymia 0.969 - also result so high seems unprobable but possibly I am wrong
for reference to make debugging easier basic quantities (they agreed in my code and yours)
true positives =206422
true negatives =6684530
false positives =0
false negatives =218185

and code
```

 def getPred(prediction, numb):
        return sitk.BinaryErode(prediction, [1,1,1], sitk.sitkBall, 0,numb)
prediction= py"getPred"(prediction,1)
    prediction= py"getPred"(prediction,2)
    
    labels = Dict([(1,"WHITEMATTER"),(2,"GREYMATTER") ])


 metrics = [pymMetr.CohenKappaCoefficient()
                ,pymMetr.AdjustedRandIndex()                  
                ]
                
    evaluator = pymEval.SegmentationEvaluator(metrics, labels)
    
    evaluator.evaluate(prediction, ground_truth, examplemhaDat[1])
    
    pymWrite.ConsoleWriter().write(evaluator.results)

```
result from console (I generally analyzed Whitematter for now )

![image](https://user-images.githubusercontent.com/53857487/135134471-21cee1bf-eadb-422f-a26f-ed9931977ee1.png)

Is it my mistake or bug?

**Comment by fabianbalsiger** [comment]
Hi,

I think there _might_ be a problem on your side, actually. When I run our [basic evaluation example](https://github.com/rundherum/pymia/blob/master/examples/evaluation/basic.py), I get the same values as you have for Subject_2:

```
Subject-wise results...
SUBJECT    LABEL        ADJRIND  KAPPA
Subject_1  GREYMATTER   0.286    0.301
Subject_1  WHITEMATTER  0.614    0.631
Subject_2  GREYMATTER   0.271    0.286
Subject_2  WHITEMATTER  0.619    0.640
```
I also have the same confusion matrix values as you, so I really wonder where the issue could be. What do you get when you run this minimal working example:

```
import numpy as np
import pymia.evaluation.metric as metric

cm = metric.ConfusionMatrix(np.zeros(1), np.zeros(1))  # we pass some dummy data for initialization
cm.tp = 206422
cm.tn = 6684530
cm.fp = 0
cm.fn = 218185
cm.n = cm.tp + cm.tn + cm.fp + cm.fn

ck = metric.CohenKappaCoefficient()
ck.confusion_matrix = cm
ari = metric.AdjustedRandIndex()
ari.confusion_matrix = cm

print(f'CK: {ck.calculate()}')
print(f'ARI: {ari.calculate()}')
```

I have:

```
CK: 0.640179086383726
ARI: 0.6186993800199808
```

**Comment by jakubMitura14** [comment]
Strange, all is based on confusion matrix so how one metrics will be evaluated correctly other not, never mind frankly You are my gold standard to check weather results of my package is correct,

I am developing Julia package with CUDA acceleration for medical segmentation, it is open source (although not yet ready) if you will be interested in porting it so will be available for python users let me know. I would be happy to help and will appreciate independent benchmarks if you think it will be useful for you , algorithms as far as I see scale pretty well a d even calculating all confusion matrix related metrics on 512x512x317 data I get sth like 340 microseconds generally around 1/3 millisecond for that's already loaded on GPU  and probably there is still some room for improvement,  as i am still prototyping. How does it compare to your benchmarks of evaluation for data already uploaded to operational memory?

**Comment by fabianbalsiger** [comment]
> Strange, all is based on confusion matrix so how one metrics will be evaluated correctly other not, never mind frankly You are my gold standard to check weather results of my package is correct,

Yes, it is strange. Did you run my small example? What did you get as results?

> I am developing Julia package with CUDA acceleration for medical segmentation, it is open source (although not yet ready) if you will be interested in porting it so CUDA acceleration will be available for python users let me know. I would be happy to help and will appreciate independent benchmarks if you think it will be usefull for you , algorithms as far as I see scale pretty well a even calculating all confusion matrix related metrics on 512x512x317 data I get sth like 340 microseconds generally around 1/3 millisecond for data that is already loaded on GPU and probably there is still some room for improvement, as i am still prototyping. How does it compare to your benchmarks of evaluation for data already uploaded to operational memory?

What you implement is somehow related to #33. We currently don't think there will be a lot of performance gain and, therefore, the effort is likely not worth it in our view. But I can't tell you how fast we are on such large data. What times do you get with pymia on your data?

**Comment by jakubMitura14** [comment]
I did it completely independently from #33 , I did not yet benchmarked against you as I am calling pymia from Julia and in benchmarking it will not show correct speed comparison. So I need to write the python code for it separately. Also I am planning the suite of benchamrks with pymia and possibly original Taha C++ code as I will complete disance metrics - as in those cases I expect most of performance gain.
Of course, Hovewer I was proposing tha You can just call my Julia package from Python  - Julia was build for speed and interoperability with Python, just asking now becouse as it is still in development I may encode abstaractions in a way that will be more usefull for You, so more people can use it :)

**Comment by jakubMitura14** [comment]
Your code works well, I do not understand it, If I will get the idea how is it possible I will tell :)

**Comment by fabianbalsiger** [comment]
Good to hear. We think it might be that there was some data in the memory of your jupyter notebook.

I think you could start with the [basic evaluation example](https://github.com/rundherum/pymia/blob/master/examples/evaluation/basic.py) for benchmarking. Yeah, if the performance gain is significant, we could think about calling your package. If you need help with the benchmarking, just tell me. For now, I will close the issue.
