### ISSUE TITLE
[question] how to avoid ram buildup?

### ISSUE THREAD

**Issue by neuronflow** [rundherum/pymia#48]
I am running inference on a large test set (>1200 3D brain scans) with 240x240x155.

I call the evaluator like this. Prediction and Label are lists of the label and prediction maps. Due to the large sample size, the lists become huge, the code becomes slow, and finally runs out of RAM

```
    for case, prediction, label in zip(case_ids, predictions, labels):
        evaluator.evaluate(prediction, label, case)
```

Is there a more elegant way to do this?
From my naive perspective, pymia could evaluate each image pair separately and only keep the results in RAM?

Thanks for your help!

**Comment by neuronflow** [comment]
Ah, I believe the problem is solved by rtfm :)

https://pymia.readthedocs.io/en/latest/examples.evaluation.basic.html

I was using code I wrote with Fabian back then.

**Comment by fabianbalsiger** [comment]
hey Florian, good to hear. Although, I think there is certainly room for code/speed improvements when evaluating 1200 scans...
Re-open if you have further questions.

**Comment by neuronflow** [comment]
Any suggestions? I wonder if it makes sense to parallelize the metric computation.

**Comment by fabianbalsiger** [comment]
Ah sorry, I thought it was resolved. pymia does evaluate the image pairs seperately `evaluator.evaluate(prediction, ground_truth, subject_id)` and does only keep the results in memory (which shouldn't be a problem as those are lightweight classes), so it is up to you, to handle the lists with the image pairs. You could only load parts of the image pairs?
For speed, you could try to use the `multiprocessing` of Python, although I am not entirely sure if the implementation of the evaluator will allow this (make a test w/o and w/ and compare results!). Something like this:

```
import multiprocessing as mp

evaluator = init_evaluator()

def load_and_evaluate(case_id):
   prediction = load_based_on_case_id(case_id)
   label = load_based_on_case_id(case_id)
   evaluator.evaluate(prediction, label, case_id)

pool = mp.Pool(mp.cpu_count())
pool.map(load_and_evaluate, case_ids)

results = evaluator.results
```

Please check the docs of multiprocessing, might be that my suggestion doesn't work (not tested) :-)
