### ISSUE TITLE
Torch and TensorFlow dependencies

### ISSUE THREAD

**Issue by fabianbalsiger** [rundherum/pymia#7]
The `data` package and the `deeplearning` package (see branch feat-deeplearning) depend on Torch and TensorFlow, respectively. Having these dependencies is not nice. The aim would be to "remove" those dependencies.

[setuptools offers extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), which might be a feasible way to make the two packages optional. So, we would have three pip installation variants (sorted by increasing functionality):

1) `pip install pymia`
2) `pip install pymia[data]`
3) `pip install pymia[deeplearning]` (note that this would be equal to `pip install pymia[data,deeplearning]` since `deeplearning` depends on `data`)

**Comment by alainjungo** [comment]
This has been done by version 0.2.1
